# あなたのCloudflare Pagesプロジェクト名
name = "cloudflare-app"

# 安定した過去の日付を指定
compatibility_date = "2025-07-10" 

[pages_build_output]
# その中の dir というキーに値を設定
dir = "."

# [重要] 互換性フラグを文字列の配列形式で指定
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MY_R2_BUCKET"  # コード内で env.MY_R2_BUCKET としてアクセスする名前
bucket_name = "voice" # Cloudflareダッシュボードで作成したR2バケットの実際の名前

# --- D1データベースのBinding設定 ---
[[d1_databases]]
binding = "MY_D1_DATABASE" # コード内で env.MY_D1_DATABASE としてアクセスする名前
database_name = "voice" # Cloudflareダッシュボードで作成したD1データベースの実際の名前
database_id = "uuid" # D1データベースのUUID