# あなたのCloudflare Pagesプロジェクト名
name = "cloudflare-app"

# 安定した過去の日付を指定
compatibility_date = "2025-07-10" 

# Cloudflare Pages用の設定。静的アセットがルートディレクトリにあることを示す。
pages_build_output_dir = "."

# [重要] 互換性フラグを文字列の配列形式で指定
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MY_R2_BUCKET"  # コード内で env.MY_R2_BUCKET としてアクセスする名前
bucket_name = "voice" # Cloudflareダッシュボードで作成したR2バケットの実際の名前

# --- D1データベースのBinding設定 ---
[[d1_databases]]
binding = "MY_D1_DATABASE" # コード内で env.MY_D1_DATABASE としてアクセスする名前
database_name = "voice" # Cloudflareダッシュボードで作成したD1データベースの実際の名前
database_id = "2ac0129a-3e2d-4376-ac79-f74fd74dd71c" # D1データベースのUUID